stages:
  - build_jira

variables:
  GIT_STRATEGY: fetch
  DEFAULT_RELEASE_TAG: 'latest'  # Add a default release tag in case the variable is not set

.jira_rules:
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      changes:
        - app/*

build_jira:
  stage: build_jira
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  extends: .jira_rules
  script:
    - cd app
    - |
      if [ -n "${CI_MERGE_REQUEST_ID}" ]; then
        RELEASE_TAG=$(grep "^release=" .release | cut -d "=" -f 2)
      else
        RELEASE_TAG=${RELEASE_TAG:-$DEFAULT_RELEASE_TAG} 
      fi
    - >
      /kaniko/executor 
      --context "${CI_PROJECT_DIR}/app" 
      --dockerfile "${CI_PROJECT_DIR}/app/Dockerfile"
      --build-arg RELEASE_TAG=$RELEASE_TAG
      --destination "${CI_REGISTRY_IMAGE}/jira-software:${RELEASE_TAG}"
      --destination "${CI_REGISTRY_IMAGE}/jira-software:${CI_COMMIT_SHA}"